### PR TITLE
SOR - Fix missing path combinations

### LINKED ISSUE #2161: SOR - Fix algorithm not expanding all path combinations
Current SOR algorithm is not properly expanding all expected swap path combinations.
It's a fundamental flaw that prevents it from properly finding the best path, specially when pool with Normalized Liquidity non-proportional to actual pool Liquidity are being considered (e.g. GyroE pools).

### PR DESCRIPTION
**Pull request by brunoguerios**
Closes #2161

### CODE REVIEW

File: modules/sor/lib/pathGraph/pathGraph.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { PathGraphEdgeData, PathGraphTraversalConfig } from './pathGraphTypes';
 import { BasePool } from '../poolsV2/basePool';
 import { PathLocal } from '../path';
 
-const DEFAULT_MAX_PATHS_PER_TOKEN_PAIR = 4;
+const DEFAULT_MAX_PATHS_PER_TOKEN_PAIR = 3;
```
Comment (brunoguerios) [inline modules/sor/lib/pathGraph/pathGraph.ts:6]: @franzns - moved it back to 3 because this fix might increase the number of paths significantly and I think it would be better to check the load on production before bumping to 4 again.
ps: 3 should be enough to cover the scenario we saw issues these past few days

File: modules/sor/lib/pathGraph/pathGraph.ts [hunk 2]
```diff
@@ -86,25 +86,47 @@ export class PathGraph {
...
+                }
+                rankCombinations = newCombinations;
+            }
+
+            // Now iterate through all combinations and expand paths
+            for (const ranks of rankCombinations) {
+                try {
+                    const path = this.expandTokenPathWithRanks({
+                        tokenPath: tokenPath,
+                        ranks: ranks,
```
Comment (brunoguerios) [inline modules/sor/lib/pathGraph/pathGraph.ts:113]: This is the main change.
Instead of passing a single `tokenPairIndex` to the expandTokenPath logic, we're now passing an array of `ranks`.
This is done for all possible combinations within the `maxPathsPerTokenPair` limit.
