### PR TITLE
SOR - Fix Boosted GyroE test data

### LINKED ISSUE #1871: SOR - Not able to swap ECLP back into range
From @franzns 
> hey, got something for you https://beets.fi/pools/sonic/v3/0x0af8ea4de2ecfb962cdbb66033a46afe99836994
created this v3 boosted eclp on sonic and pushed it out of range with a swap. For some reason, it doesnt let me push it back into it via direct swap. Seems the SOR doesnt return a path
I should be able to swap wS->USDC at a very good rate with that pool :smile:
whats even more interesting, I can push it further out of range, I can swap USDC->wS :rolling_on_the_floor_laughing:
of course rekting me in the process

### PR DESCRIPTION
**Pull request by brunoguerios**
Closes #1871

Note: the issue itself was actually a wrong user input which did not need changes to the SOR to be handled, but it helped identify a few improvements to test data generation for boosted gyroe pools, which were applied on this PR.

### CODE REVIEW

**Comment by brunoguerios** [comment]
> ### ⚠️ No Changeset found

Since it's only test related changes, there's no need for a release/changeset.

File: modules/sor/lib/path.ts [hunk 1]
```diff
@@ -93,8 +93,8 @@ export class PathWithAmount extends PathLocal {
                 this.inputAmount = amounts[0];
                 this.outputAmount = this.swapAmount;
             }
-        } catch {
-            throw new Error('Invalid path, swap amount exceeds maximum for pool');
+        } catch (error) {
+            throw new Error('Invalid swap path with error: ' + error);
```
Comment (MattPereira) [inline modules/sor/lib/path.ts:97]: yay for better error handling :clap:

**Review by MattPereira — APPROVED** [review]
I like how you took opportunity to improve test data even tho issue turned out to be user error :muscle:

**Review by mkflow27 — APPROVED** [review]
More test data is always great.
