### PR TITLE
SOR - Fix swap through LBP

### LINKED ISSUE #1986: SOR - Can't find path through sDAI/s-KPK on GNOSIS
https://balancer.fi/pools/gnosis/v2/0x40d2cbc586dd8df50001cdba3f65cd4bbc32d596000200000000000000000154/swap

### PR DESCRIPTION
**Pull request by brunoguerios**
Closes #1986

### CODE REVIEW

File: modules/sor/utils/data.ts [hunk 1]
```diff
@@ -58,7 +59,7 @@ async function getPoolsByIds(
     poolIds: string[],
 ): Promise<PrismaPoolAndHookWithDynamic[]> {
     const pools = await prisma.prismaPool.findMany({
-        where: { id: { in: poolIds }, chain, protocolVersion, type },
+        where: { id: { in: poolIds }, chain, protocolVersion, type: { in: [...type.in, 'LIQUIDITY_BOOTSTRAPPING'] } },
```
Comment (johngrantuk) [inline modules/sor/utils/data.ts]: Does 'LIQUIDITY_BOOTSTRAPPING' need to be manually added here if its already in type?

**Review by johngrantuk — APPROVED** [review]

File: modules/sor/utils/data.ts (hunk 1 above)
Comment (brunoguerios) [reply modules/sor/utils/data.ts]: Ops - I added it to type while investigating the issue and forgot to remove. 
It shouldn't be there, otherwise when we query "primary" pools, we'll also query LBPs, which is not the goal.
I'll remove it from there 👍
