### PR TITLE
SOR - Fix gyroE swap exact in by taking fee before rates

### LINKED ISSUE #1735: SOR - Suboptimal path found to swap sDAI <> bCSPX
Reported by @Zen-Maxi 

for [this pool](https://gnosisscan.io/address/0x1e28a0450865274873bd5485a1e13a90f5f59cbd#readContract) the SOR seems to be ignoring the ECLP and taking into account the CG price at 597.99 - 178.61 bCSPX at 8.9% price impact

Image

but if I try to force the swap thru the ECLP pool I get the same CG price at 597.99 - 189.81 bCSPX at 2.5% price impact

Image

Any reason the best route isn’t being used?

### PR DESCRIPTION
**Pull request by brunoguerios**
Closes #1735

### CODE REVIEW

File: modules/sor/sorV2/lib/poolsV2/gyroE/gyroEPool.ts [hunk 1]
```diff
@@ -148,11 +148,11 @@ export class GyroEPool implements BasePool {
             y: currentInvariant,
         };
         // swapAmount from PathWithAmount does not take rate into account - this step fixes scale18 so it properly considers rates
-        const swapAmountLive = new PoolTokenWithRate(tokenIn, swapAmount.amount, tIn.index, tIn.rate);
-        const inAmount = this.subtractSwapFeeAmount(swapAmountLive);
+        const swapAmountLessFee = this.subtractSwapFeeAmount(swapAmount);
+        const inAmountLive = new PoolTokenWithRate(tokenIn, swapAmountLessFee.amount, tIn.index, tIn.rate);
```
Comment (brunoguerios) [inline modules/sor/sorV2/lib/poolsV2/gyroE/gyroEPool.ts:152]: Fees should be taken before applying rates. Last PR introduced this error and this one fixes it.
