### PR TITLE
Sor fix swap exact out rates

### LINKED ISSUE #1688: SOR - Exact in/out returning much different results
Reported by @franzns 

Image
Image

### PR DESCRIPTION
**Pull request by brunoguerios**
Closes #1688

Note: another one related to `scale18` not being "live" (i.e. properly considering rates)

### CODE REVIEW

File: modules/sor/sorV2/lib/poolsV2/gyroE/gyroEPool.ts [hunk 1]
```diff
@@ -178,6 +181,8 @@ export class GyroEPool implements BasePool {
         mutateBalances?: boolean,
     ): TokenAmount {
         const { tIn, tOut } = this.getPoolTokens(tokenIn, tokenOut);
+        // swapAmount from PathWithAmount does not take rate into account - this step fixes scale18 so it properly considers rates
+        const swapAmountLive = new PoolTokenWithRate(tokenOut, swapAmount.amount, tOut.index, tOut.rate);
```
Comment (brunoguerios) [inline modules/sor/sorV2/lib/poolsV2/gyroE/gyroEPool.ts:185]: This was the main fix. It makes sure rates will be properly applied to `swapAmount`

**Review by franzns — APPROVED** [review]
